# Configuration for judecoind
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'judecoind --help' for all available options.

data-dir=/var/lib/judecoin
log-file=/var/log/judecoin/bitjudecoin.log
log-level=0
